Fix DHTID inner serialization
learning-at-home/hivemind pull request #172
Opened 2021-03-04 17:50 UTC by leshanbog

Using msgpack to create bytes from DHT keys to avoid pickle compatibility issue.

2021-03-04 18:00 UTC, justheuristic commented
@leshanbog
note: you could add a special serialization rule for python tuples, similarly to this syntax:
https://github.com/learning-at-home/hivemind/blob/master/hivemind/dht/storage.py#L9-L10

2021-03-04 21:25 UTC, justheuristic approved these changes

2021-03-05 07:42 UTC, mryab requested changes

2021-03-05 07:42 UTC, mryab commented on tests/test_routing.py
> +from hivemind.utils.serializer import MSGPackSerializer
Import not required

2021-03-05 07:42 UTC, mryab commented on hivemind/utils/serializer.py
> +            return msgpack.ExtType(cls._MsgpackExtTypeCodeTuple, data)
We'd better leave a comment to explain why tuples need to be handled separately

2021-03-05 09:14 UTC, mryab approved these changes

2021-03-05 09:16 UTC, merged