Test
learning-at-home/hivemind pull request #186
Opened 2021-03-17 18:35 UTC by deniskamazur

2021-03-17 23:10 UTC, justheuristic approved these changes
Good point, let's use binaries in install mode, we just need to figure out how best to store them

2021-03-18 09:39 UTC, justheuristic commented
:note from @mryab :
- check version when downloading (i.e. not just latest)
- do not re-download p2pd if control sum matches the reference

2021-03-18 09:58 UTC, mryab requested changes

2021-03-18 09:58 UTC, mryab commented on setup.py
> +    if build:
In essence, you have two functions with entirely different code. It's best to separate them into two functions with different names

2021-03-19 14:46 UTC, mryab requested changes

2021-03-19 14:46 UTC, mryab commented on setup.py
> +        for chunk in iter(lambda: f.read(4096), b""):
Move 4096 to a constant or at least an argument with default value

2021-03-19 19:11 UTC, mryab approved these changes

2021-03-19 19:12 UTC, mryab commented on setup.py
> +        print('Downloading Peer to Peer Daemon')
Will fix that when merging to master

2021-03-19 19:13 UTC, merged