Support auxiliary participants in AllReduceProtocol
learning-at-home/hivemind pull request #260
Opened 2021-05-11 21:32 UTC by foksly

Resolve #233

2021-05-13 20:00 UTC, mryab requested changes

2021-05-14 12:41 UTC, foksly commented on hivemind/client/averaging/allreduce.py
> +        self.num_senders = len([mode for mode in modes if mode != Mode.AUX])
`TypeError: object of type 'generator' has no len()`

2021-05-14 12:56 UTC, mryab requested changes

2021-05-14 12:56 UTC, mryab commented on hivemind/client/averaging/allreduce.py
> +                print(f'{self.endpoint} - NOT SENDING STUFF {self.peer_modes}')
Remove debug print or convert to a logger call (IMO the first is preferable)

2021-05-14 12:56 UTC, mryab commented on hivemind/client/averaging/allreduce.py
> +        assert self.peer_modes[self.endpoint] != AveragingMode.AUX, "auxiliary peers are disallowed from sending tensors"
```suggestion
        assert self.peer_modes[self.endpoint] != AveragingMode.AUX, "Auxiliary peers are disallowed from sending tensors"
```

2021-05-14 12:56 UTC, mryab commented on hivemind/client/averaging/allreduce.py
> +        assert self.peer_modes[self.endpoint] != AveragingMode.AUX, "auxiliary peers do not have local tensors for sending"
```suggestion
        assert self.peer_modes[self.endpoint] != AveragingMode.AUX, "Auxiliary peers do not have local tensors for sending"
```

2021-05-14 12:56 UTC, mryab commented on hivemind/client/averaging/__init__.py
> +            weights, throughputs, modes_ix, user_gathered = zip(*map(self.serializer.loads, group_info.gathered))
I think it's still worth changing, not sure if `_ix` is a common suffix for indices

2021-05-14 13:37 UTC, mryab approved these changes

2021-05-19 16:19 UTC, yhn112 requested changes

2021-05-19 16:19 UTC, yhn112 commented on hivemind/client/averaging/__init__.py
>          assert isinstance(weight, (int, float)) and weight > 0, f"Expected a positive int/float, got {type(weight)}"
Seems like this assert should be in the "else" branch of the next "if".

2021-05-20 17:50 UTC, foksly commented
Investigation report:
__Problem:__ Test with 2 aux and 2 client peers failed once in a few hundred attempts
__Cause:__ both aux peers entered matchmaking with __exactly__ the same dht_time -- and refused to request each other because of ">=" comparison (to be fixed in subsequent commit)


Example debug prints (from https://github.com/learning-at-home/hivemind/pull/263 )


```
=================================== FAILURES ===================================
___________________________ test_allreduce_once[2-2] ___________________________
n_clients = 2, n_aux = 2

    @pytest.mark.forked
    @pytest.mark.parametrize("n_clients", [0, 1, 2])
    @pytest.mark.parametrize("n_aux", [0, 1, 2])
    def test_allreduce_once(n_clients, n_aux):
>       _test_allreduce_once(n_clients, n_aux)

tests/test_averaging.py:86: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

n_clients = 2, n_aux = 2

    def _test_allreduce_once(n_clients, n_aux):
        dht = hivemind.DHT(start=True, endpoint=f'{hivemind.LOCALHOST}:*')
    
        n_peers = 4
        modes = [AveragingMode.CLIENT] * n_clients + [AveragingMode.AUX] * n_aux + [AveragingMode.NODE] * (n_peers - n_clients - n_aux)
        # random.shuffle(modes)
    
        tensors1 = [torch.randn(123), torch.zeros(3)]
        tensors2 = [torch.rand(123), torch.ones(3)]
        tensors3 = [-torch.rand(123), torch.arange(3).to(torch.float32)]
        tensors4 = [torch.randn(123) ** 3, torch.arange(3).to(torch.float32) / 2]
        peer_tensors = [tensors1, tensors2, tensors3, tensors4]
    
        reference = [sum(tensors[i] for tensors, mode in zip(peer_tensors, modes)
                     if mode != AveragingMode.AUX) / max(1, n_peers - n_aux) for i in range(len(tensors1))]
    
        averagers = [hivemind.DecentralizedAverager(tensors, dht=dht, target_group_size=4, averaging_expiration=15,
                                                    prefix='mygroup', listen=mode != AveragingMode.CLIENT, listen_on='127.0.0.1:*',
                                                    auxiliary=(mode == AveragingMode.AUX), start=True)
                     for tensors, mode in zip(peer_tensors, modes)]
        futures = []
        for averager in averagers:
            futures.append(averager.step(wait=False))
        for future in futures:
            result = future.result()
            for averager in averagers:
>               assert averager.endpoint in result, f"{modes}"
E               AssertionError: [<AveragingMode.CLIENT: 1>, <AveragingMode.CLIENT: 1>, <AveragingMode.AUX: 2>, <AveragingMode.AUX: 2>]
E               assert '127.0.0.1:41813' in {'127.0.0.1:44459': None, 'client::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa': None, 'client::59909d38-6f42-4340-adfa-87d57d5f6c3c': None}
E                +  where '127.0.0.1:41813' = DecentralizedAverager(127.0.0.1:41813).endpoint

tests/test_averaging.py:70: AssertionError
----------------------------- Captured stdout call -----------------------------
QQclient::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa - current queue = {}
QQclient::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa - awaiting queue update
QQclient::59909d38-6f42-4340-adfa-87d57d5f6c3c - current queue = {}
QQclient::59909d38-6f42-4340-adfa-87d57d5f6c3c - awaiting queue update
QQ127.0.0.1:44459 - current queue = {}
QQ127.0.0.1:44459 - awaiting queue updateQQ127.0.0.1:41813 - current queue = {}

QQ127.0.0.1:41813 - awaiting queue update
QQclient::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa - current queue = {}
QQclient::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa - awaiting queue update
QQ127.0.0.1:44459 - current queue = {}
QQ127.0.0.1:44459 - awaiting queue update
QQclient::59909d38-6f42-4340-adfa-87d57d5f6c3c - current queue = {}
QQclient::59909d38-6f42-4340-adfa-87d57d5f6c3c - awaiting queue update
QQ127.0.0.1:41813 - current queue = {}
QQ127.0.0.1:41813 - awaiting queue update
QQ127.0.0.1:41813 - current queue = {}
QQ127.0.0.1:41813 - awaiting queue update
QQ127.0.0.1:44459 - current queue = {}
QQ127.0.0.1:44459 - awaiting queue update
QQclient::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa - current queue = {'127.0.0.1:44459': ValueWithExpiration(value=1621532347.506267, expiration_time=1621532347.506267)}
QQclient::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa - yielding 127.0.0.1:44459
client::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa - REQUEST TO 127.0.0.1:44459
QQclient::59909d38-6f42-4340-adfa-87d57d5f6c3c - current queue = {'127.0.0.1:44459': ValueWithExpiration(value=1621532347.506267, expiration_time=1621532347.506267)}
QQclient::59909d38-6f42-4340-adfa-87d57d5f6c3c - yielding 127.0.0.1:44459
client::59909d38-6f42-4340-adfa-87d57d5f6c3c - REQUEST TO 127.0.0.1:44459
127.0.0.1:44459 - incoming request from client::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa (time=1621532332.5730908)
127.0.0.1:44459 - accepted request from client::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa
client::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa - joining the group of 127.0.0.1:44459; waiting for peers
127.0.0.1:44459 - incoming request from client::59909d38-6f42-4340-adfa-87d57d5f6c3c (time=1621532332.5739517)
127.0.0.1:44459 - accepted request from client::59909d38-6f42-4340-adfa-87d57d5f6c3c
client::59909d38-6f42-4340-adfa-87d57d5f6c3c - joining the group of 127.0.0.1:44459; waiting for peers
QQ127.0.0.1:41813 - current queue = {'127.0.0.1:44459': ValueWithExpiration(value=1621532347.506267, expiration_time=1621532347.506267)}
QQ127.0.0.1:41813 - awaiting queue update
QQ127.0.0.1:44459 - current queue = {'127.0.0.1:41813': ValueWithExpiration(value=1621532347.506267, expiration_time=1621532347.506267)}
QQ127.0.0.1:44459 - awaiting queue update
QQ127.0.0.1:41813 - current queue = {'127.0.0.1:44459': ValueWithExpiration(value=1621532347.506267, expiration_time=1621532347.506267)}
QQ127.0.0.1:41813 - awaiting queue update
QQ127.0.0.1:44459 - current queue = {'127.0.0.1:41813': ValueWithExpiration(value=1621532347.506267, expiration_time=1621532347.506267)}
QQ127.0.0.1:44459 - awaiting queue update
QQ127.0.0.1:41813 - current queue = {'127.0.0.1:44459': ValueWithExpiration(value=1621532347.506267, expiration_time=1621532347.506267)}
(...repeated several more times...)

QQ127.0.0.1:41813 - awaiting queue update
QQ127.0.0.1:44459 - current queue = {'127.0.0.1:41813': ValueWithExpiration(value=1621532347.506267, expiration_time=1621532347.506267)}
QQ127.0.0.1:44459 - awaiting queue update
QQ127.0.0.1:41813 - current queue = {'127.0.0.1:44459': ValueWithExpiration(value=1621532347.506267, expiration_time=1621532347.506267)}
QQ127.0.0.1:41813 - awaiting queue update
QQ127.0.0.1:44459 - current queue = {'127.0.0.1:41813': ValueWithExpiration(value=1621532347.506267, expiration_time=1621532347.506267)}
QQ127.0.0.1:44459 - awaiting queue update
127.0.0.1:44459 - beginning allreduce because time is up, group: {'client::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa': endpoint: "client::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa"
schema_hash: "K\250\212\000@B\331\376g\321#k-\336\364*\020<\254~"
expiration: 1621532347.5698905
gather: "\224\313?\360\000\000\000\000\000\000\300\001\304\001\300"
client_mode: true
, 'client::59909d38-6f42-4340-adfa-87d57d5f6c3c': endpoint: "client::59909d38-6f42-4340-adfa-87d57d5f6c3c"
schema_hash: "K\250\212\000@B\331\376g\321#k-\336\364*\020<\254~"
expiration: 1621532347.571211
gather: "\224\313?\360\000\000\000\000\000\000\300\001\304\001\300"
client_mode: true
} (plus 127.0.0.1:44459)target size = 4 (time=1621532347.5079453)
client::59909d38-6f42-4340-adfa-87d57d5f6c3c - beginning alreduce
client::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa - beginning alreduce
127.0.0.1:44459 - finished processing request from client::59909d38-6f42-4340-adfa-87d57d5f6c3c
127.0.0.1:44459 - finished processing request from client::2dd4f14d-6b9a-43b2-b754-52b4c29b21fa
QQ127.0.0.1:41813 - current queue = {}
QQ127.0.0.1:41813 - awaiting queue update
QQ127.0.0.1:41813 - current queue = {'127.0.0.1:44459': ValueWithExpiration(value=1621532362.5062153, expiration_time=1621532362.5062153)}
QQ127.0. [...]

2021-05-20 21:15 UTC, yhn112 approved these changes

2021-05-20 21:15 UTC, justheuristic approved these changes

2021-05-21 01:04 UTC, merged