A bunch of typing annotations fixes
learning-at-home/hivemind pull request #325
Opened 2021-07-16 17:56 UTC by yhn112

2021-07-16 18:11 UTC, borzunov commented on hivemind/averaging/partition.py
> +from typing import Sequence, AsyncIterable, Tuple, Optional, TypeVar, Union, AsyncIterator, Type, Deque, List
(optional) Consider sorting the imports, but this may be out of scope of this PR.

2021-07-16 18:28 UTC, borzunov commented on hivemind/utils/crypto.py
> +            raise ValueError(f"Expected an RSA public key, got {str(key)}")
```suggestion
            raise ValueError(f"Expected an RSA public key, got {str(loaded_key)}")
```

2021-07-16 18:29 UTC, borzunov approved these changes

2021-07-17 08:52 UTC, mryab requested changes

2021-07-17 08:52 UTC, mryab commented on hivemind/dht/traverse.py
> -    visited_nodes: Dict[DHTID, Set[DHTID]] = dict(visited_nodes or {})  # nodes that were chosen for get_neighbors call
I'm not sure that mutating the input object is the intended (or expected) behavior here, so it's best left as is

2022-01-21 00:00 UTC, borzunov commented on pyproject.toml
> +
```suggestion
```

2022-01-21 00:01 UTC, borzunov approved these changes

2022-01-21 00:02 UTC, borzunov commented
In my opinion, the best strategy would be to achieve zero mypy errors on some module (e.g., hivemind.utils), then expand that to one more module, etc.

2022-01-21 00:59 UTC, yhn112 commented
It is impossible to achieve 
> zero mypy errors

(in any module of the project) without

> making the code too verbose and actually making it less readable as a result.

2022-01-21 01:26 UTC, borzunov commented
Isn't there an alternative mypy config or an alternative type checker that doesn't require that?

2023-08-28 19:19 UTC, closed without merging