Reformat imports with isort
learning-at-home/hivemind pull request #326
Opened 2021-07-16 21:57 UTC by yhn112

2021-07-17 00:33 UTC, borzunov commented
Please consider https://pycqa.github.io/isort/docs/configuration/black_compatibility.html

2021-07-17 00:38 UTC, borzunov commented on .github/workflows/check-style.yml
> +      - uses: isort/isort-action@master
nit: \n

2021-07-17 00:38 UTC, borzunov commented on pyproject.toml
> +line_length = 119
nit: \n

2021-07-17 00:39 UTC, borzunov approved these changes

2021-07-17 06:55 UTC, mryab requested changes
Thank you! Please add 
1) Info about using isort to the style part of the contribution guide
2) Isort as a dependency in requirements-dev
3) Relevant configuration options to avoid mixing third- and first-party modules and splitting "as" statements
4) Rerun isort with this new configuration
After that, we will be able to proceed with merging the PR

2021-07-17 06:55 UTC, mryab commented on examples/albert/run_trainer.py
> +from arguments import AlbertTrainingArguments, AveragerArguments, CollaborationArguments, DatasetArguments
Imports of local modules should not get mixed with third-party libraries. Consider configuring options such as [known-first-party](https://pycqa.github.io/isort/docs/configuration/options.html#known-first-party) and [known-local-folder](https://pycqa.github.io/isort/docs/configuration/options.html#known-local-folder)

2021-07-17 06:55 UTC, mryab commented on hivemind/moe/server/connection_handler.py
> +from hivemind.proto import runtime_pb2_grpc as runtime_grpc
Maybe [combine_as_imports](https://pycqa.github.io/isort/docs/configuration/options.html#combine-as-imports) might be helpful in this case

2021-07-17 06:55 UTC, mryab commented on tests/test_dht_node.py
> +from test_utils.dht_swarms import launch_star_shaped_swarm, launch_swarm_in_separate_processes
test_utils also needs to be recognized as a first-party/local module

2021-07-19 03:12 UTC, mryab approved these changes

2021-07-19 03:12 UTC, mryab commented on pyproject.toml
> +[tool.isort]
```suggestion
required-version = "21.6b0"

[tool.isort]
```

2021-07-19 17:48 UTC, justheuristic approved these changes

2021-07-28 20:29 UTC, justheuristic commented
Perhaps the time has come to re-isort and merge this :)

2021-07-29 11:48 UTC, merged